name             'chef-vault'
maintainer       'Opscode, Inc.'
maintainer_email 'cookbooks@opscode.com'
license          'Apache 2.0'
description      'Installs the chef-vault gem'
version          '1.0.2'
