name             'chef-vault'
maintainer       'Chef Software, Inc.'
maintainer_email 'cookbooks@getchef.com'
license          'Apache 2.0'
description      'Installs the chef-vault gem and provides chef_vault_item recipe helper'
version          '1.1.2'
